---
- name: Enabled and Started Chrony
  service:
    name: chronyd
    enabled: true
    state: started

- name: Restart Firewalld
  service: 
    name: firewalld
    state: restarted

- name: Started and Enabled NGINX
  service:
    name: nginx
    enabled: true
    state: started

- name: Started and Enabled PHP-FPM
  service:
    name: php-fpm
    enabled: true
    state: started

- name: Restart NGINX
  service: 
    name: nginx
    state: restarted

- name: Restart PHP
  service: 
    name: php-fpm
    state: restarted

- name: Started and Enabled Dovecot
  service:
    name: dovecot
    enabled: true
    state: started   

    