---
#############################1-BLOCK#############################################
- name: System preparation
  include_tasks: general_settings.yaml

- name: Web Server Setup NGINX + PHP + MariaDB
  include_tasks: nginx_php_mariadb.yaml

- name: Installing and configuring PostfixAdmin
  include_tasks: deploy_postfixadmin.yaml

#############################2-BLOCK#############################################


#- name: Installing and configuring Postfix
#  include_tasks: deploy_postfix.yaml

#- name: Setting up Dovecot
#  include_tasks: deploy_dovecot.yaml

#############################3-BLOCK#############################################


#- name: Installing and configuring Roundcube Webmail
#  include_tasks: deploy_roundcube.yaml

#################################################################################